Repository woowacourse/service-apply, pull requests merged in 2020-09, with the labels that each got.

#56 feat(apply): implement applicant information input form
  frontend/.prettierrc
  frontend/public/assets/logo/logo_full_dark.png
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/components/form/BirthField.vue
  frontend/src/components/form/Button.vue
  frontend/src/components/form/CheckBox.vue
  frontend/src/components/form/Field.vue
  frontend/src/components/form/Form.vue
  frontend/src/components/form/GenderField.vue
  frontend/src/components/form/Label.vue
  frontend/src/components/form/Radio.vue
  frontend/src/components/form/RuleField.vue
  frontend/src/components/form/SummaryCheckField.vue
  frontend/src/components/form/TextField.vue
  frontend/src/components/form/TextInput.vue
  frontend/src/components/form/index.js
  frontend/src/router/index.js
  frontend/src/utils/validation/birth.js
  frontend/src/utils/validation/common.js
  frontend/src/utils/validation/index.js
  frontend/src/utils/validation/regist.js
  frontend/src/views/Regist.vue
  frontend/src/views/constants.js
Labels: 지원 화면

#55 feat(selection) : implement selection management view
  src/main/kotlin/apply/application/ApplicantService.kt
  src/main/kotlin/apply/application/RecruitmentService.kt
  src/main/kotlin/apply/domain/applicant/Applicant.kt
  src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt
  src/main/kotlin/apply/domain/applicant/Gender.kt
  src/main/kotlin/apply/ui/admin/BaseLayout.kt
  src/main/kotlin/apply/ui/admin/SelectionView.kt
  src/main/kotlin/apply/ui/admin/SelectionsView.kt
  src/main/kotlin/support/Dates.kt
  src/main/kotlin/support/Views.kt
  src/test/kotlin/apply/domain/applicant/ApplicantRepositoryTest.kt
Labels: 관리 화면

#57 feat(apply): implement the recruitment writing view
  frontend/package-lock.json
  frontend/src/api/recruitments.js
  frontend/src/components/empty.txt
  frontend/src/components/form/TextField.vue
  frontend/src/components/form/TextInput.vue
  frontend/src/router/index.js
  frontend/src/utils/validation/regist.js
  frontend/src/views/RecruitmentRegister.vue
  frontend/src/views/empty.txt
  frontend/vue.config.js
  src/main/kotlin/apply/application/RecruitmentItemService.kt
  src/main/kotlin/apply/domain/recruitmentitem/RecruitmentItem.kt
  src/main/kotlin/apply/domain/recruitmentitem/RecruitmentItemRepository.kt
  src/main/kotlin/apply/ui/api/RecruitmentRestController.kt
  src/test/kotlin/apply/domain/recruitmentitem/RecruitmentItemRepositoryTest.kt
Labels: 지원 화면

#58 feat(evaluation): implement evaluation management view
  src/main/kotlin/apply/application/EvaluationService.kt
  src/main/kotlin/apply/domain/evaluation/Evaluation.kt
  src/main/kotlin/apply/domain/evaluation/EvaluationRepository.kt
  src/main/kotlin/apply/domain/evaluation/dto/EvaluationResponse.kt
  src/main/kotlin/apply/ui/admin/BaseLayout.kt
  src/main/kotlin/apply/ui/admin/EvaluationView.kt
  src/test/kotlin/apply/application/EvaluationServiceTest.kt
Labels: 관리 화면

#59 feat(apply): implement recruitment list view
  frontend/package-lock.json
  frontend/src/App.vue
  frontend/src/components/RecruitItem.vue
  frontend/src/router/index.js
  frontend/src/views/Recruits.vue
Labels: 지원 화면

#93 feat(evaluation): implement the evaluation save function
  src/main/kotlin/apply/application/EvaluationDtos.kt
  src/main/kotlin/apply/application/EvaluationService.kt
  src/main/kotlin/apply/domain/evaluation/EvaluationRepository.kt
  src/main/kotlin/apply/domain/evaluation/dto/EvaluationResponse.kt
  src/main/kotlin/apply/domain/evaluationItem/EvaluationItem.kt
  src/main/kotlin/apply/ui/admin/evaluation/EvaluationForm.kt
  src/main/kotlin/apply/ui/admin/evaluation/EvaluationItemForm.kt
  src/main/kotlin/apply/ui/admin/evaluation/EvaluationsFormView.kt
  src/main/kotlin/apply/ui/admin/evaluation/EvaluationsView.kt
  src/main/kotlin/support/views/Components.kt
  src/test/kotlin/apply/application/EvaluationServiceTest.kt
  src/test/kotlin/apply/ui/admin/evaluation/EvaluationItemFormTest.kt
Labels: 관리 화면, 기능
