Repository woowacourse/service-apply, pull requests merged in 2021-09, with the labels that each got.

#314 feat(mail): implement the mail target api among evaluation targets
  src/main/kotlin/apply/application/EvaluationDtos.kt
  src/main/kotlin/apply/application/MailTargetService.kt
  src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswers.kt
  src/main/kotlin/apply/domain/evaluationtarget/EvaluationTarget.kt
  src/main/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepository.kt
  src/main/kotlin/apply/ui/api/EvaluationTargetRestController.kt
  src/test/kotlin/apply/application/MailTargetServiceTest.kt
  src/test/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepositoryTest.kt
  src/test/kotlin/apply/ui/api/EvaluationTargetRestControllerTest.kt
Labels: 기능, 관리 화면

#319 refactor(apply): abstract controlled component logic
  frontend/src/components/form/BirthField/BirthField.js
  frontend/src/components/form/BirthField/BirthField.module.css
  frontend/src/components/form/CheckBox/CheckBox.js
  frontend/src/components/form/GenderField/GenderField.js
  frontend/src/components/form/RuleField/RuleField.js
  frontend/src/components/form/RuleField/RuleField.module.css
  frontend/src/components/form/RuleField/RuleField.stories.js
  frontend/src/components/form/TextField/TextField.js
  frontend/src/components/form/TextField/TextField.module.css
  frontend/src/components/form/index.js
  frontend/src/hooks/useForm.js
  frontend/src/hooks/useFormContext.js
  frontend/src/pages/ApplicantRegister/ApplicantRegister.js
  frontend/src/pages/ApplicantRegister/ApplicantRegister.module.css
  frontend/src/pages/ApplicationRegister/ApplicationRegister.js
  frontend/src/pages/ApplicationRegister/ApplicationRegister.module.css
  frontend/src/pages/Login/Login.js
  frontend/src/pages/Login/Login.module.css
  frontend/src/pages/PasswordEdit/PasswordEdit.js
  frontend/src/pages/PasswordEdit/PasswordEdit.module.css
  frontend/src/pages/PasswordFind/PasswordFind.js
  frontend/src/pages/PasswordFind/PasswordFind.module.css
  frontend/src/provider/FormProvider/FormProvider.js
  frontend/src/provider/FormProvider/InputField.js
  frontend/src/provider/FormProvider/ResetButton.js
  frontend/src/provider/FormProvider/SubmitButton.js
  frontend/src/utils/validation/birth.js
  frontend/src/utils/validation/email.js
  frontend/src/utils/validation/name.js
  frontend/src/utils/validation/password.js
  frontend/src/utils/validation/phoneNumber.js
  frontend/src/utils/validation/url.js
Labels: 지원 화면, 리팩터링

#324 feat(apply): scroll to top when user move the page
  frontend/src/App.js
  frontend/src/components/ScrollToTop/ScrollToTop.js
Labels: 리팩터링

#320 refactor(apply): constantize messages and paths
  frontend/src/App.js
  frontend/src/components/MainFooter/MainFooter.js
  frontend/src/components/MainHeader/MainHeader.js
  frontend/src/components/PrivateRoute/PrivateRoute.js
  frontend/src/components/RecruitItem/RecruitItem.js
  frontend/src/components/form/GenderField/GenderField.js
  frontend/src/components/form/SummaryCheckField/SummaryCheckField.js
  frontend/src/constants/messages.js
  frontend/src/constants/path.js
  frontend/src/constants/tab.js
  frontend/src/hooks/useFormContext.js
  frontend/src/hooks/useRecruitmentContext.js
  frontend/src/hooks/useTokenContext.js
  frontend/src/pages/ApplicantRegister/ApplicantRegister.js
  frontend/src/pages/ApplicationRegister/ApplicationRegister.js
  frontend/src/pages/Login/Login.js
  frontend/src/pages/PasswordEdit/PasswordEdit.js
  frontend/src/pages/PasswordFind/PasswordFind.js
  frontend/src/pages/PasswordFindResult/PasswordFindResult.js
  frontend/src/pages/Recruits/Recruits.js
  frontend/src/provider/FormProvider/InputField.js
  frontend/src/provider/FormProvider/ResetButton.js
  frontend/src/utils/date/index.js
  frontend/src/utils/route/query.js
Labels: 지원 화면, 리팩터링

#323 feat(cheater): implement cheater registration form view
  src/main/kotlin/apply/application/CheaterDtos.kt
  src/main/kotlin/apply/ui/admin/cheater/CheaterForm.kt
  src/main/kotlin/apply/ui/admin/cheater/CheaterFormDialog.kt
  src/main/kotlin/apply/ui/admin/cheater/CheatersView.kt
  src/main/kotlin/support/views/Components.kt
Labels: 기능, 관리 화면

#364 feat(apply): change the birthday input type
  frontend/src/components/form/BirthField/BirthField.js
  frontend/src/components/form/TextInput/TextInput.module.css
Labels: 기능, 지원 화면

#350 feat(apply): automatically convert to phone number format
  frontend/src/components/BaseItem/BaseItem.js
  frontend/src/components/CommonItem/CommonItem.js
  frontend/src/hooks/useApplicantRegisterForm.js
  frontend/src/hooks/useForm.js
  frontend/src/pages/ApplicantRegister/ApplicantRegister.js
  frontend/src/pages/ApplicationRegister/ApplicationRegister.js
  frontend/src/pages/PasswordFind/PasswordFind.js
  frontend/src/utils/format/date.js
  frontend/src/utils/format/phoneNumber.js
Labels: 기능, 지원 화면
